name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Lint [androidApp]
        run: ./gradlew :androidApp:lintDebug
      - name: Lint [androidUI]
        run: ./gradlew :androidUI:lintDebug
      - name: Lint [shared]
        run: ./gradlew :shared:lintDebug

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build [androidApp]
        run: ./gradlew :androidApp:build

  unit-test:
    name: Unit Test
    needs: [ lint, build ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Test [androidApp]
        run: ./gradlew :androidApp:testDebugUnitTest
      - name: Test [androidUI]
        run: ./gradlew :androidUI:testDebugUnitTest
      - name: Test [shared]
        run: ./gradlew :shared:testDebugUnitTest

  instrumentation-test:
    name: Instrumentation Test
    needs: [ lint, build ]
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-33
      - name: run tests
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          arch: x86_64
          profile: Nexus 5
          script: ./gradlew :androidApp:connectedDebugAndroidTest
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew :androidUI:connectedDebugAndroidTest

  release-dry-run:
    name: Release dry run
    needs: [ unit-test, instrumentation-test ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build [androidApp]
        run: ./gradlew :androidApp:assembleRelease