name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Lint
        run: .github/ci/android/lint.sh

  release-dry-run:
    name: Release dry run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Release dry run
        run: ./gradlew :androidApp:assembleRelease

  unit-test:
    name: Unit Test
    needs: [ lint, release-dry-run ]
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Unit Test
        run: .github/ci/android/unit_test.sh

  instrumentation-test:
    name: Instrumentation Test
    needs: [ lint, release-dry-run ]
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: pixel5-31-aosp
      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: default
          arch: x86_64
          profile: pixel_5
          avd-name: Pixel_5_API_31_AOSP
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: default
          arch: x86_64
          profile: pixel_5
          avd-name: Pixel_5_API_31_AOSP
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          pre-emulator-launch-script: .github/ci/android/instrumentation_test_before.sh
          script: .github/ci/android/instrumentation_test.sh
